language: php
php:
 - '5.4'
 - '5.5'
 - '5.6'
 - '7.0'
 - '7.1'
before_script: composer up
script: ./vendor/bin/phpunit --verbose --coverage-text
after_success:
 - travis_retry php vendor/bin/coveralls -v